baseURL = 'https://pahri.netlify.app/'
languageCode = 'id'
title = 'My New Hugo Site'
# defaultContentLanguage = 'en'

[params]
contentTypeName = 'post'
showMenuItems = 4
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false
autoCover = true
showLastUpdated = true
updatedDatePrefix = 'Updated'
readingTime = false
# Toc = false # default
TocTitle = 'Daftar Isi' 

menuMore = 'Show more'
readMore = 'Read more'
readOtherPosts = 'Read other posts'
newerPosts = 'Newer posts'
olderPosts = 'Older posts'
missingContentMessage = 'Page not found...'
missingBackButtonLabel = 'Back to home page'
minuteReadingTime = 'min read'
words = 'words'

  
[params.logo]
  logoText = 'Terminal!'
  logoHomeLink = '/'
  

[markup.tableOfContents]
  startLevel = 1
  endLevel = 6
  class = 'toc'

  
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about'

[[menu.main]]
  identifier = 'lorem'
  name = 'Lorem'
  url = '/freak%01~'
  
  
[[module.imports]]
  path = 'github.com/adityatelange/hugo-PaperMod'

  
